#LIST CONTAINING LISTS OF METRICS AND DIMENSIONS API NAMES TO RUN A REPORT ON
list:
  - Dimension:
      - country
      - pageTitle
      - deviceModel
      - deviceCategory
      - dateHour
      - sourceMedium
    Metric:
      - totalUsers
      - bounceRate
#  - Dimension:
#      - pageTitle
#    Metric:
#      - totalUsers
#  - Dimension:
#      - deviceModel
#      - deviceCategory
#    Metric:
#      - totalUsers
#  - Dimension:
#      - dateHour
#    Metric:
#      - totalUsers
#      - averageSessionDuration
#      - bounceRate
#  - Dimension:
#      - sourceMedium
#    Metric:
#      - totalUsers