#DICTIONARY CONTAINING DIMENSIONS AND METRICS ACROSS MULTIPLE REPORTS
#DO NOT GENERATE REPORTS FOR MORE THAN 9 METRICS OR DIMENSIONS AT ONE TIME
list:
  - Dimension:
      #LIST OF DIMENSIONS
    Metric:
      #LIST OF METRICS
  #Multiple such reports